using BMS_Scheduler.Common;
using Serenity.Services;
using System;
using System.Collections.Generic;

namespace BMS_Scheduler
{
    public class TelecastTypeRequest : ServiceRequest
    {
        public long ProgramId { get; set; }
        public int? EpisodeNumber { get; set; }
        public long? SegmentNumber { get; set; }
        public DateTime TelecastTime { get; set; }
    }

    public class TelecastTypeResponse : ServiceResponse
    {
        public ProgramTelecastType TelecastType { get; set; }
        public int? EpisodeNumber { get; set; }
    }

    public class DailyRundownExistanceRequest : ServiceRequest
    {
        public DateTime RundownDate { get; set; }
    }

    public class DailyRundownExistanceResponse : ServiceResponse
    {
        public Int64 RundownId { get; set; }
    }

    //public class DailyRundownSaveRequest : ServiceRequest
    //{
    //    public List<DailyRundownRow> DailyRundowns { get; set; }
    //    public DateTime RundownDate { get; set; }
    //}

    //public class DailyRundownSaveResponse : ServiceResponse
    //{
    //    public List<DailyRundownRow> DailyRundowns { get; set; }
    //}

    public class DailyRundownExportRequest : ServiceRequest
    {
        public Int64 Id { get; set; }
        public string FileName { get; set; }
        public List<string> ExportColumns { get; set; }
    }

    public class DailyRundownExportResponse : ServiceResponse
    {
        public List<DailyRundownInformation> Rundowns { get; set; }

    }

    public class DailyRundownInformation
    {
        public string Category { get; set; }
        public string TimeCode { get; set; }
        public string Duration { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Remarks { get; set; }
    }

    public class DailyRundownTimeSegmentRequest : ServiceRequest
    {
        public DateTime RundownDate { get; set; }
    }

    public class DailyRundownTimeSegmentResponse : ServiceResponse
    {
        //public DailyRundownTimeSegmentRow DailyRundown { get; set; }
        public String Message { get; set; }
        public Boolean IsSuccess { get; set; }
    }

    public class DailyRundownDataRequest : ServiceRequest
    {
        public DateTime RundownDate { get; set; }
        public Int64? TimeSegmentId { get; set; }
        public Int64? PositionId { get; set; }
    }

    public class DailyRundownDataResponse : ServiceResponse
    {
        //public List<DailyRundownRow> DailyRundowns { get; set; }
    }


    public class ContentDatabaseRequest : ServiceRequest
    {
        public DateTime RundownDate { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public int? ProgramId { get; set; }
        public int? ProgramCategoryId { get; set; }
        public int? SpotPositionId { get; set; }

    }

    public class ContentDatabaseResponse : ServiceResponse
    {
        //public List<ClientTvcRow> ContentDatabase { get; set; }
    }

    public class DailyRundownTimeSegmentSaveRequest : ServiceRequest
    {
        //public DailyRundownTimeSegmentRow DailyRundown { get; set; }
        public Int64? TimeSlotDetailId { get; set; }
    }

    public class DailyRundownTimeSegmentSaveResponse : ServiceResponse
    {
        //public DailyRundownTimeSegmentRow DailyRundown { get; set; }
        public bool IsSuccess { get; set; } = true;
        public String Message { get; set; }
    }

    public class AutoGeneratedCodeConfigRequest : ServiceRequest
    {
        public Common.AutoGeneratedCodeConfiguration ConfigurationFor { get; set; }
    }

    public class AutoGeneratedCodeConfigResponse : ServiceResponse
    {
        //public CodeGenerationConfigRow CodeConfiguration { get; set; }
    }

    public class ApproverRequest : ServiceRequest
    {
        public Common.ApprovalProcess approvalProcess { get; set; }
    }

    public class ApproverResponse : ServiceResponse
    {
        //public List<ApproverInformationRow> Approvers { get; set; }
    }

    public class ApprovalFlowRequest : ServiceRequest
    {
        public Common.ApprovalProcess approvalProcess { get; set; }
        public long? ApprovalFlowDetailId { get; set; }
        public int? ApprovalStatusId { get; set; }
        public long? ApplicationId { get; set; }
    }

    public class ApprovalFlowResponse : ServiceResponse
    {
        //public ApprovalFlowDetailRow ApprovalFlow { get; set; }
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }

    public class ApprovalFlowScopeRequest : ServiceRequest
    {
        public Common.ApprovalProcess approvalProcess { get; set; }

    }

    public class ApprovalFlowScopeResponse : ServiceResponse
    {
        public Boolean IsRequired { get; set; }
    }

    public class TimeSegmentRequest : ServiceRequest
    {
        public DateTime RundownDate { get; set; }
        public int FromTime { get; set; }
        public int ToTime { get; set; }

    }

    public class TimeSegmentResponse : ServiceResponse
    {
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }

    public class DailyRundownTimeSegmentCopyRequest : ServiceRequest
    {
        public DateTime RundownDate { get; set; }
        public Int64 RundownTimeSegmentId { get; set; }

    }

    public class DailyRundownTimeSegmentCopyResponse : ServiceResponse
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }

    //public class DailyRundownTimeSegmentPositionSaveRequest : ServiceRequest
    //{
    //    public DailyRundownTimeSegmentPositionRow Position { get; set; }

    //}

    //public class DailyRundownTimeSegmentPositionSaveResponse : ServiceResponse
    //{
    //    public List<DailyRundownTimeSegmentPositionRow> Positions { get; set; }
    //    public bool IsSuccess { get; set; }
    //    public string Message { get; set; }
    //}

}
