namespace BMS_Scheduler {
    export interface AutoGeneratedCodeConfigRequest extends Serenity.ServiceRequest {
        ConfigurationFor?: BMS_Scheduler.Common.AutoGeneratedCodeConfiguration;
    }
}
