namespace BMS_Scheduler.Common {
    export enum AutoGeneratedCodeConfiguration {
        Invoice = 10,
        TimeCode = 20,
        Client = 30,
        Agency = 40,
        Ro = 50,
        Program = 60,
        ClientContract = 70
    }
    Serenity.Decorators.registerEnumType(AutoGeneratedCodeConfiguration, 'BMS_Scheduler.Common.AutoGeneratedCodeConfiguration', 'AutoGeneratedCodeConfiguration');
}
