using Serenity;
using Serenity.ComponentModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;

namespace _Ext
{
    public partial class AutoGeneratedCodeEditorAttribute : CustomEditorAttribute
    {
        public const string Key = "_Ext.AutoGeneratedCodeEditor";

        public AutoGeneratedCodeEditorAttribute()
            : base(Key)
        {
        }

        public object CodeFor
        {
            get { return GetOption<object>("CodeFor"); }
            set { SetOption("CodeFor", value); }
        }

        public string Message
        {
            get { return GetOption<string>("Message"); }
            set { SetOption("Message", value); }
        }
    }
}
